'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    'sınıfı tarafından otomatik olarak oluşturuldu.
    'Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    'komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    '''<summary>
    '''  Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cylops_s_Cheat_Loader.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        '''  CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property efso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("efso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property Girişşş() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Girişşş", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property Profile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Profile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property Res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Imports System.Windows.Forms
        '''Imports System.Reflection
        '''
        '''&lt;Assembly: AssemblyTitle(&quot;*Title*&quot;)&gt; 
        '''&lt;Assembly: AssemblyDescription(&quot;*Description*&quot;)&gt; 
        '''&lt;Assembly: AssemblyCompany(&quot;*Company*&quot;)&gt; 
        '''&lt;Assembly: AssemblyProduct(&quot;*Product*&quot;)&gt; 
        '''&lt;Assembly: AssemblyCopyright(&quot;*Copyright*&quot;)&gt; 
        '''&lt;Assembly: AssemblyTrademark(&quot;*Trademark*&quot;)&gt; 
        '''&lt;Assembly: AssemblyVersion(&quot;*version*&quot;)&gt; 
        '''&lt;Assembly: AssemblyFileVersion(&quot;*fversion*&quot;)&gt; 
        '''
        '''Module X
        '''    Sub Main()
        '''    	MessageBox.Show(&quot;&quot;, &quot;&quot;, MessageBoxButtons.OK, MessageBoxIco [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        '''</summary>
        Friend ReadOnly Property RHDiscription() As String
            Get
                Return ResourceManager.GetString("RHDiscription", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
